### ISSUE TITLE
🤔  Q. 강의상세와 파일의 매핑과정

### ISSUE THREAD

**Issue by kyeumd** [f-lab-edu/infrun#20]
## 목표

강의 상세와 등록되는 실제 파일을 매핑한다.

## 질문사항

request 처리 시 multipart 형태의 file 자체에 강의 상세 정보를 매핑 할 수 없음
-> 따라서 강의 상세 Json에 어떤 file이 매핑되어야 하는지 매핑해야하는데
-> file명으로 매핑하는 방식 채택

1. file을 저장
2. 저장된 file List를 반복문을 통해 파일상세의 fileName과 매핑
3. 이름을 찾아 id를 매핑
4. 파일상세 저장 시 이름에 매핑된 file Id 를 찾아 같이 저장

이 과정이 일어나기 위해서는 파일명이 중복되지 않아야 함

여기서 의문점 발생 

Q. 이 파일명 중복 체크가 과연 필요한 행위인가?에 대한 의문
(상세를 매핑하기 위해 억지로 중복체크를 하는것이 아닌가 라는 생각이 문득 듦)

## 고려해본 방법

- multipart file 자체의 UUID 를 부착하여 저장 (의견)
- multipart file 자체의 식별자 존재여부 (실패)
- 강의-강의상세-파일 이 구조에서 동일한 강의 내부의 파일명 중복은 일어나도 문제 없는 구조

**Comment by chicori3** [comment]
파일명 중복체크가 왜 불필요하다고 생각하시나요?

**Comment by kyeumd** [comment]
파일명 자체가 강의-강의상세-파일 구조로 되어 있기도 하고 
그런 구조로 인해서 다른 영상을 같은 이름으로 올린다고 할지라도 등록에 문제가 없도록 하기 위함으로 생각했습니다

**Comment by chicori3** [comment]
클라이언트가 똑같은 강의 파일을 3개 올린다면 한 강의 챕터에 똑같은 강의가 3개 등록될텐데
이것은 의도적인 것이 아니라면 실수일 확률이 높을 것 같습니다
그럼 영속화될 때 무의미하게 3개의 파일이 저장될 것이고 저희는 soft delete로 처리하기로 했는데 사소하지만 리소스 낭비일 수도 있다고 생각이 들어요

**Comment by kyeumd** [comment]
반대로 생각해보니 그것 자체가 실수 일 수 있다는 말도 일리가 있다고 생각드네요 파일명을 토대로 정합성 검사를 하는 것으로 가져가도록 구현하면 되겠군요 감사합니다

**Comment by chicori3** [comment]
@kyeumd 
동겸님 제가 밥먹으면서 떠오른 생각인데 이미 알고 계실 것 같지만 적어봅니다
파일명 검증을 하려면 강사 ID와 함께 해야할 것 같아요
강사 A의 파일명과 강사 B의 파일명은 똑같을 수 있는데 이걸 제가 놓친 것 같아요

**Comment by kyeumd** [comment]
@chicori3 
강사가 다를 경우 요청이 따로 들어와서 문제 없을 것으로 생각되는데 어떤 관점으로 파일명의 중복 검증을 얘기하시는 걸까요 ?
실제 저장되는 레포도 강사 id별로 따로 폴더가 만들어질 예정이라 강사ID와 함께 중복체크를 해야하는 상황을 정확하게 이해를 못했습니다.

**Comment by chicori3** [comment]
레포가 다른게 무슨 의미인지는 잘 모르겠습니다만 DB 테이블에는 강사 ID와 파일이 함께 들어가지 않나요?

**Comment by kyeumd** [comment]
실제 저장되는 레파지토리를 의미한거였습니다. DB테이블에는 강의 상세에 파일id가 매핑되고 파일 테이블에는 강의나 강사에 대한 정보가 적재되지 않습니다 !

**Comment by chicori3** [comment]
아 네 다시 ERD 보니까 잘못생각하고 있었네요 감사합니다
