### ISSUE TITLE
🤔 멤버 Role을 반환해주는 역할의 책임 

### ISSUE THREAD

**Issue by kyeumd** [f-lab-edu/infrun#22]
## 목표

강의 등록 시 Role을 확인하고 Teacher 가  아닌 경우 Exception 처리

## 고려사항

1. Member Facade 에게 메세지 
2. Member Facade의 역할의 범위?
- Member Role을 반환해주는 것 까지
- Member Role이 Teacher인지 체크 해주고 exception을 발생시키는 isTeacher을 수행 -> domain에서는 teacher 여부만 체크
3. Lecture 내부에서 Member resource로의 직접적인 접근은 지양

결론 : Member Facade의 책임을 어디까지 책정할 것인가 ?

**Comment by chicori3** [comment]
유저 역할을 검증하는 것은 인증/인가 영역인데 이는 Spring Security에서 처리할 수 있습니다
FilterChain에 hasRole을 설정하고 실제로 Member를 조회하는것은 UserDetailService로 구현할 수 있어요

**Comment by kyeumd** [comment]
DB에 접근해야한다고만 생각했네요 Spring Security 관련내용 참고하고 다시 의견 공유드리겠습니다 !

**Comment by chicori3** [comment]
제 PR에 해당 기능 있으니까 그거 보셔도 될 것 같습니다
