### ISSUE TITLE
🤔 Q. CQRS Command와 Query의 Naming Rule

### ISSUE THREAD

**Issue by kyeumd** [f-lab-edu/infrun#23]
## 목표

CQRS로 분리한 Command 와 Query Processor의 이름 분할

## 고려사항

- 현재 Command 를 Processor 로 작성한 상태

1. CommandProcessor
2. QueryProcessor

로 명시적으로 커맨드 역할을 하는 프로세서/ 쿼리 역할을 하는 프로세서로 구분하는 방식 채택 제안

**Comment by chicori3** [comment]
말씀하신대로 정하면 될 것 같습니다
