### ISSUE TITLE
📄 Git Merge 정책 제안 

### ISSUE THREAD

**Issue by chicori3** [f-lab-edu/infrun#26]
## 목표

Git Merge 정책 제안

## 고려사항

Feat -> Develop Merge할 때 Squash & Merge 방식으로 정하는 것이 괜찮을 것 같습니다.

Feat 브랜치는 기능 구현을 위한 브랜치이며 해당 기능의 세세한 작업 사항은 PR에서 확인할 수 있고
실제 Develop 브랜치에서는 해당 기능 구현을 하나의 커밋으로 묶어 관리할 수 있습니다.

Develop 브랜치 운용 중에 문제가 발생하면 feat 브랜치 커밋 내역을 기준으로 reset 시켜 확인할 수 있는 것이 더 용이할 것 같습니다.

## 참고자료

https://meetup.nhncloud.com/posts/122

**Comment by kyeumd** [comment]
저도 동일한 생각입니다.
Feat -> Develop Merge할 때 는 Squash & Merge 방식으로
Develop -> Main Merge할 때는 Merge 방식을 채택하는 것이 좋을듯합니다.
