### ISSUE TITLE
❗  Spring Security 권한 처리 Exception

### ISSUE THREAD

**Issue by kyeumd** [f-lab-edu/infrun#32]
## 목표

DefaultHandlerExceptionResolver 의 기본 Exception처리 Response 

## 상황

1. Request 요청의 int 형식 데이터 존재
2. 해당 데이터를 String 형태로 착오 입력
3. 내부적으로 HttpMessageNotReadableException 발생
4. 응답 ErrorCdoe : UN_AUTHORIZATION로 유효하지 않은 인증 정보 Response

## 해결방안

- Spring Security 내부 동작 방식 확인 필요

**Comment by chicori3** [comment]
![image](https://github.com/f-lab-edu/infrun/assets/40778768/3c7e7e6f-1a7b-4f89-96b9-1fe7d1226727)

저는 Validator로 인한 에러가 제대로 반환되어서 그러는데
어떤 컨트롤러의 어떤 요청을 보냈는지 자세히 설명해주실 수 있을까요?

**Comment by kyeumd** [comment]
![image](https://github.com/f-lab-edu/infrun/assets/77428439/cdc9abcd-b18d-463d-aa70-677c502d48a5)
lecture controller의 lecture 등록하는 /lecture Post요청이였습니다.
lectureLevel 항목이
![image](https://github.com/f-lab-edu/infrun/assets/77428439/d3b3c607-3a04-4460-818b-30bed2ed6515)
이렇게 validation 걸린 상태입니다(요청은 String으로 보냄)

**Comment by chicori3** [comment]
SecurityConfig의 filterChain 부분도 캡쳐해주실 수 있나요?

**Comment by kyeumd** [comment]
![image](https://github.com/f-lab-edu/infrun/assets/77428439/1dfc59d1-83f0-4093-8e1b-3417fc074f8c)
(여담으로 member/** 지워져있는 이유는 처음에 chain 형식으로 했는데 response로 인증정보에 대한게 넘어와서 chain형태로 작성하면 적용 안되는가 하고 잠깐 바꿔서 해본겁니다)

**Comment by chicori3** [comment]
<img width="1002" alt="image" src="https://github.com/f-lab-edu/infrun/assets/40778768/931d435e-411b-4028-8881-f77524397d28">

스프링 블로그에서 원인을 찾을 수 있었습니다. 에러가 발생했을 때 기본적으로 에러 페이지를 반환하는데 (서버 띄우면 나오는 Whitelabel 페이지), 해당 페이지에 대한 권한도 authenticated()로 설정되어 있어서 그렇습니다. 때문에 400이 발생한 것이 맞지만, 에러 페이지에 대한 권한이 없기 때문에 Unauthorized가 발생한 거에요. 저희는 API 서버라 데이터만 주고 받기 때문에 따로 설정을 안했는데 제가 놓친 것 같습니다. 😅

`.dispatcherTypeMatchers(DispatcherType.ERROR)`을 추가하면 정상적으로 400 에러를 반환합니다.
추가적으로 Jackson이 JSON 포맷에서 데이터를 직렬화할 때 타입이 맞지 않는 경우 hibernate validate가 작동하지 않습니다.
그전에 말씀하신 HttpMessageNotReadableException 예외가 발생하게 돼요. 
이 때는 HttpMessageConversionException을 처리하는 ExceptionHandler를 정의해서 이미 명시해둔 Response.fail(ErrorCode.Invalid_Parameter)를 반환하게 하면 될 것 같습니다.

**Comment by kyeumd** [comment]
해당 내용 확인 감사합니다!
HttpMessageConversionException 관련 부분도 무슨 내용인지 이해했습니다 !
