### ISSUE TITLE
🤔 강의 등록시 멤버 Role Check에 대한 Unit Testing

### ISSUE THREAD

**Issue by kyeumd** [f-lab-edu/infrun#34]
## 목표

강의 등록시 멤버 Role Check에 대한 Unit Testing

## 현재상황

1. @PreAuthorize("hasRole('ROLE_TEACHER')") 을 통해 권한을 부여
2. Postman으로 Member 등록 후 h2 database 직접 수정하여 Role TEACHER 로 변경
3. login 하여 Token 반환
4. 해당 Token을 Header의 Authorization에 Bearer prefix를 사용하여 요청 처리
5. 권한 직접 테스트 완료

이 상황에서 유닛 테스팅을 위한 작업을 동일하게 진행하려 하였으나
Member 객체의 Role을 코드 내부에서 컨트롤 할 수 있는 방법이 없어서 고민중입니다.

이렇게 flow 처리 방식이 아닌 Spring Security + JWT 자체적인 Testing 방법이나 다른 더 나은 방법이 있다면 공유 부탁드립니다!

**Comment by chicori3** [comment]
이게 스프링 시큐리티가 적용되면서 Presentation 레이어 테스트가 힘들어서 저도 고민 중에 있습니다.
일단 동겸님의 케이스에서는 Teacher Role을 가진 유저를 미리 DB에 저장하는 data.sql 같은 기능을 사용해서 하면 될 것 같아요.

**Comment by kyeumd** [comment]
아 그런 방법이 있겠군요 감사합니다!
