### ISSUE TITLE
📄  TestCode Repository Stub 공통화 제안

### ISSUE THREAD

**Issue by kyeumd** [f-lab-edu/infrun#35]
## 목표

TestCode의 Repository Stub을 공통화 하여 재사용성을 높인다.

## 고려사항

Lecture Review를 등록하는 과정에서 Member와 Lecture에 대한 정보를 가져오는 작업이 필요합니다.

그래서 단위 테스트를 위한 Repository Stub 클래스가 필요한데
이미 시안님이 작성한 MemberRepository에 대한 Stub이 이미 있는 것을 토대로

각 도메인의 Repository Stub을 공통으로 추출하여 재사용성을 높이는 방법은 어떨까요?

**Comment by chicori3** [comment]
제가 Repository 들을 객체로 만들어둔 것도 재사용성을 염두에 둔 것이라 좋은 것 같아요.
다만 테스트 패키지를 어떻게 모듈화할 것인지도 고민이 필요할 것 같습니다.

**Comment by kyeumd** [comment]
현재로써는 운영 코드와 동일하게 Common package의 persistence 로 가져가는 것은 어떨까요?

**Comment by chicori3** [comment]
사소하지만 common 보다는 utils에 persistence가 더 나은 것 같습니다
