### ISSUE TITLE
🤔 PreAuthorize 403 에러 해결방안

### ISSUE THREAD

**Issue by chicori3** [f-lab-edu/infrun#49]
## 목표

역할 변경 후에 (USER -> TEACHER) `@PreAuthorize("hasRole('TEACHER')")` 메서드  호출 시 403 에러 코드가 발생하는 문제 해결하기.

## 현재상황

역할이 변경되어도, Jwt에 저장된 ROLE이 변경되지 않아 403 에러가 발생하는 문제가 있습니다.
이 문제를 해결하기 위해 제가 생각한 해결 방안은 다음과 같습니다.

1. 강사용 회원가입을 분리한다
2. 회원에서 강사로 역할 변경 시 재로그인이 되도록 로그아웃 처리를 한다

다른 의견이 있으시다면 주시면 감사하겠습니다.
의견이 수렴되면 해당 작업 들어가겠습니다!  🫡

**Comment by kyeumd** [comment]
기존의 JWT의 방식과 뭔가 바뀐 부분이 있는건가요? 기존에는 역할 변경에 따른 JWT 토큰의 ROLE도 함께 변경이 되었던 것 같은데
어떤 과정이 있었기에 해당 문제가 발생하게 된건지 해당 문제를 직접적으로 해결하는 방법은 없는걸까요?
로그인 시점에 JWT 토큰이 생성되고 해당 토큰에 ROLE에 대한 정보가 함께 포함되어 있던거라면 기존에는 어떻게 동작했기에 변경에 대한 감지가 일어난걸까요?

**Comment by chicori3** [comment]
`PrincipalAuthentication` 을 사용하기 위해 `UserDetailsService` 로직을 수정하긴 했지만,
Jwt 발급 로직은 기존과 달라진 점은 하나도 없습니다.🙇‍♂️

로그인 시 로그인한 정보를 토큰에 담게 되는데, 이 때 ROLE_USER가 토큰에 담겨있게 되고 이후 DB에서 직접 TEACHER로 변경해도
토큰은 변경되지 않기 때문에 이슈가 발생한 것입니다.
아마 DB에서 TEACHER로 변경 후에 다시 로그인을 하셔서 발급된 토큰으로 테스트를 수행해서 되지 않았을까요?🤔

토큰을 재발급받으려면 다시 로그인을 하거나, 매 요청마다 토큰을 바꿔주는 방법이 있을 것 같습니다!

**Comment by kyeumd** [comment]
말씀하신대로 가입 후 로그인 전에 데이터를 변경하고 로그인 하니 정상적으로 되네요
가입하고 로그인 하고 바꿨다고 생각하고있었는데 제가 착각 했었나 봅니다😅 
현재 Member로만 가입이 되도록 되어있는데 제안하신 방법을 포함하여

1. 강사용 회원가입을 분리한다.
2. 멤버로 가입 후 강사 자격을 신청하여 내부적인 검토 후 등록한다.

크게 이 두가지 방법이 있을 것으로 예상됩니다.
처음에 해당 비즈니스에 대해 내부적으로 검토 했던 결과는 검증된 강사가 있다는 전제하에 그렇게 작성 되었던 거긴 하지만 실제 비즈니스 적인 처리가 필요할 것으로 판단됩니다.

제안주신 2번 방법인 회원에서 강사로 변경된다는 것에 대한 부분은 
내부적으로 강사 자격을 획득하는 경로를 만든다는 얘기가 포함된 얘기인 걸까요? 

제가 생각해본 방법으로는 강사자격을 신청하고 Admin Role에서 내부적인 심사를 거쳐 강사 자격으로 변경하고 토큰도 업데이트를 하는 과정이 좋을 듯 한데 이렇게하면 공수가 좀 많이 들어가게 될 것 같습니다.
1. 토큰이 update가 가능한 구조인지 
2. 사용자가 로그아웃하여 토큰을 업데이트 할 필요가 없는지 체크
이런 추가적인 작업을 고려한다면

시안님이 제안해주신 1번 방법도 충분히 고려 할 수 있을 것으로 생각됩니다. 🧐

**Comment by chicori3** [comment]
네 확인 감사합니다.
회원에서 강사로 변경되는 부분은 MemberController에 강사 신청 핸들러를 따로 작성해서 역할을 변경하는 방법으로 생각하고 있습니다.
말씀해주신대로 아직 ADMIN에 대한 정책 등은 정하지 않았고, 다른 기능 구현을 우선해야하니 현재로는 역할 변경을 신청하면 바로 승인되는 프로세스로 가정하고, 새롭게 로그인을 요청하는 쪽으로 서로 이해하고 진행하면 될 것 같습니다. 😄

이후에 토큰 업데이트는 refresh token 을 고려할 때 토큰 업데이트에 대한 방식과 정책을 같이 고려해보겠습니다. 🫡
